# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  system: ./system
  vscode: ./tools/vscode.yml
  chrome: ./tools/chrome.yml
  gh: ./tools/gh-cli.yml
  intellij: ./tools/intellij.yml
  cursor: ./tools/cursor.yml
  windsurf: ./tools/windsurf.yml
  antigravity: ./tools/antigravity.yml
  claude: ./tools/claude.yml
  docker: ./tools/docker.yml
  git: ./tools/git.yml
  node: ./tools/node.yml
  sdkman: ./tools/sdkman.yml
  container: ./container
  ci: ./ci

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true
