# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  system: ./system
  vscode: ./tools/vscode.yml
  chrome: ./tools/chrome.yml
  gh: ./tools/gh-cli.yml
  intellij: ./tools/intellij.yml
  ci: ./ci

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true
