# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  check-taskfile:
    desc: Validate all Taskfile YAML syntax
    cmds:
      - task --list-all
    silent: true

  lint:
    desc: Lint YAML files (requires yamllint)
    cmds:
      - yamllint .
    silent: true
